/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckInSuccessRouteImport } from './routes/check-in-success'
import { Route as KioskRouteImport } from './routes/kiosk'
import { Route as LibrarianRouteImport } from './routes/librarian'
import { Route as LibrarianLoginRouteImport } from './routes/librarian-login'
import { Route as StudentRouteImport } from './routes/student'
import { Route as LibrarianIndexRouteImport } from './routes/librarian.index'
import { Route as LibrarianAnalyticsRouteImport } from './routes/librarian.analytics'
import { Route as LibrarianDevicesRouteImport } from './routes/librarian.devices'
import { Route as LibrarianKiosksRouteImport } from './routes/librarian.kiosks'
import { Route as LibrarianReportsRouteImport } from './routes/librarian.reports'
import { Route as LibrarianSettingsRouteImport } from './routes/librarian.settings'
import { Route as LibrarianStudentsRouteImport } from './routes/librarian.students'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as StudentCheckInRouteImport } from './routes/student.check-in'
import { Route as StudentDevicesRouteImport } from './routes/student.devices'
import { Route as StudentHistoryRouteImport } from './routes/student.history'
import { Route as StudentProfileRouteImport } from './routes/student.profile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInSuccessRoute = CheckInSuccessRouteImport.update({
  id: '/check-in-success',
  path: '/check-in-success',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskRoute = KioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrarianRoute = LibrarianRouteImport.update({
  id: '/librarian',
  path: '/librarian',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrarianLoginRoute = LibrarianLoginRouteImport.update({
  id: '/librarian-login',
  path: '/librarian-login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrarianIndexRoute = LibrarianIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LibrarianRoute,
} as any)
const LibrarianAnalyticsRoute = LibrarianAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => LibrarianRoute,
} as any)
const LibrarianDevicesRoute = LibrarianDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => LibrarianRoute,
} as any)
const LibrarianKiosksRoute = LibrarianKiosksRouteImport.update({
  id: '/kiosks',
  path: '/kiosks',
  getParentRoute: () => LibrarianRoute,
} as any)
const LibrarianReportsRoute = LibrarianReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => LibrarianRoute,
} as any)
const LibrarianSettingsRoute = LibrarianSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LibrarianRoute,
} as any)
const LibrarianStudentsRoute = LibrarianStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => LibrarianRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCheckInRoute = StudentCheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => StudentRoute,
} as any)
const StudentDevicesRoute = StudentDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => StudentRoute,
} as any)
const StudentHistoryRoute = StudentHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/check-in-success': typeof CheckInSuccessRoute
  '/kiosk': typeof KioskRoute
  '/librarian': typeof LibrarianRouteWithChildren
  '/librarian-login': typeof LibrarianLoginRoute
  '/student': typeof StudentRouteWithChildren
  '/librarian/analytics': typeof LibrarianAnalyticsRoute
  '/librarian/devices': typeof LibrarianDevicesRoute
  '/librarian/kiosks': typeof LibrarianKiosksRoute
  '/librarian/reports': typeof LibrarianReportsRoute
  '/librarian/settings': typeof LibrarianSettingsRoute
  '/librarian/students': typeof LibrarianStudentsRoute
  '/student/check-in': typeof StudentCheckInRoute
  '/student/devices': typeof StudentDevicesRoute
  '/student/history': typeof StudentHistoryRoute
  '/student/profile': typeof StudentProfileRoute
  '/librarian/': typeof LibrarianIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/check-in-success': typeof CheckInSuccessRoute
  '/kiosk': typeof KioskRoute
  '/librarian-login': typeof LibrarianLoginRoute
  '/librarian/analytics': typeof LibrarianAnalyticsRoute
  '/librarian/devices': typeof LibrarianDevicesRoute
  '/librarian/kiosks': typeof LibrarianKiosksRoute
  '/librarian/reports': typeof LibrarianReportsRoute
  '/librarian/settings': typeof LibrarianSettingsRoute
  '/librarian/students': typeof LibrarianStudentsRoute
  '/student/check-in': typeof StudentCheckInRoute
  '/student/devices': typeof StudentDevicesRoute
  '/student/history': typeof StudentHistoryRoute
  '/student/profile': typeof StudentProfileRoute
  '/librarian': typeof LibrarianIndexRoute
  '/student': typeof StudentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/check-in-success': typeof CheckInSuccessRoute
  '/kiosk': typeof KioskRoute
  '/librarian': typeof LibrarianRouteWithChildren
  '/librarian-login': typeof LibrarianLoginRoute
  '/student': typeof StudentRouteWithChildren
  '/librarian/analytics': typeof LibrarianAnalyticsRoute
  '/librarian/devices': typeof LibrarianDevicesRoute
  '/librarian/kiosks': typeof LibrarianKiosksRoute
  '/librarian/reports': typeof LibrarianReportsRoute
  '/librarian/settings': typeof LibrarianSettingsRoute
  '/librarian/students': typeof LibrarianStudentsRoute
  '/student/check-in': typeof StudentCheckInRoute
  '/student/devices': typeof StudentDevicesRoute
  '/student/history': typeof StudentHistoryRoute
  '/student/profile': typeof StudentProfileRoute
  '/librarian/': typeof LibrarianIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/check-in-success'
    | '/kiosk'
    | '/librarian'
    | '/librarian-login'
    | '/student'
    | '/librarian/analytics'
    | '/librarian/devices'
    | '/librarian/kiosks'
    | '/librarian/reports'
    | '/librarian/settings'
    | '/librarian/students'
    | '/student/check-in'
    | '/student/devices'
    | '/student/history'
    | '/student/profile'
    | '/librarian/'
    | '/student/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/check-in-success'
    | '/kiosk'
    | '/librarian-login'
    | '/librarian/analytics'
    | '/librarian/devices'
    | '/librarian/kiosks'
    | '/librarian/reports'
    | '/librarian/settings'
    | '/librarian/students'
    | '/student/check-in'
    | '/student/devices'
    | '/student/history'
    | '/student/profile'
    | '/librarian'
    | '/student'
  id:
    | '__root__'
    | '/'
    | '/check-in-success'
    | '/kiosk'
    | '/librarian'
    | '/librarian-login'
    | '/student'
    | '/librarian/analytics'
    | '/librarian/devices'
    | '/librarian/kiosks'
    | '/librarian/reports'
    | '/librarian/settings'
    | '/librarian/students'
    | '/student/check-in'
    | '/student/devices'
    | '/student/history'
    | '/student/profile'
    | '/librarian/'
    | '/student/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckInSuccessRoute: typeof CheckInSuccessRoute
  KioskRoute: typeof KioskRoute
  LibrarianRoute: typeof LibrarianRouteWithChildren
  LibrarianLoginRoute: typeof LibrarianLoginRoute
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in-success': {
      id: '/check-in-success'
      path: '/check-in-success'
      fullPath: '/check-in-success'
      preLoaderRoute: typeof CheckInSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk': {
      id: '/kiosk'
      path: '/kiosk'
      fullPath: '/kiosk'
      preLoaderRoute: typeof KioskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/librarian': {
      id: '/librarian'
      path: '/librarian'
      fullPath: '/librarian'
      preLoaderRoute: typeof LibrarianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/librarian-login': {
      id: '/librarian-login'
      path: '/librarian-login'
      fullPath: '/librarian-login'
      preLoaderRoute: typeof LibrarianLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/librarian/': {
      id: '/librarian/'
      path: '/'
      fullPath: '/librarian/'
      preLoaderRoute: typeof LibrarianIndexRouteImport
      parentRoute: typeof LibrarianRoute
    }
    '/librarian/analytics': {
      id: '/librarian/analytics'
      path: '/analytics'
      fullPath: '/librarian/analytics'
      preLoaderRoute: typeof LibrarianAnalyticsRouteImport
      parentRoute: typeof LibrarianRoute
    }
    '/librarian/devices': {
      id: '/librarian/devices'
      path: '/devices'
      fullPath: '/librarian/devices'
      preLoaderRoute: typeof LibrarianDevicesRouteImport
      parentRoute: typeof LibrarianRoute
    }
    '/librarian/kiosks': {
      id: '/librarian/kiosks'
      path: '/kiosks'
      fullPath: '/librarian/kiosks'
      preLoaderRoute: typeof LibrarianKiosksRouteImport
      parentRoute: typeof LibrarianRoute
    }
    '/librarian/reports': {
      id: '/librarian/reports'
      path: '/reports'
      fullPath: '/librarian/reports'
      preLoaderRoute: typeof LibrarianReportsRouteImport
      parentRoute: typeof LibrarianRoute
    }
    '/librarian/settings': {
      id: '/librarian/settings'
      path: '/settings'
      fullPath: '/librarian/settings'
      preLoaderRoute: typeof LibrarianSettingsRouteImport
      parentRoute: typeof LibrarianRoute
    }
    '/librarian/students': {
      id: '/librarian/students'
      path: '/students'
      fullPath: '/librarian/students'
      preLoaderRoute: typeof LibrarianStudentsRouteImport
      parentRoute: typeof LibrarianRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/check-in': {
      id: '/student/check-in'
      path: '/check-in'
      fullPath: '/student/check-in'
      preLoaderRoute: typeof StudentCheckInRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/devices': {
      id: '/student/devices'
      path: '/devices'
      fullPath: '/student/devices'
      preLoaderRoute: typeof StudentDevicesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/history': {
      id: '/student/history'
      path: '/history'
      fullPath: '/student/history'
      preLoaderRoute: typeof StudentHistoryRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
  }
}

interface LibrarianRouteChildren {
  LibrarianAnalyticsRoute: typeof LibrarianAnalyticsRoute
  LibrarianDevicesRoute: typeof LibrarianDevicesRoute
  LibrarianKiosksRoute: typeof LibrarianKiosksRoute
  LibrarianReportsRoute: typeof LibrarianReportsRoute
  LibrarianSettingsRoute: typeof LibrarianSettingsRoute
  LibrarianStudentsRoute: typeof LibrarianStudentsRoute
  LibrarianIndexRoute: typeof LibrarianIndexRoute
}

const LibrarianRouteChildren: LibrarianRouteChildren = {
  LibrarianAnalyticsRoute: LibrarianAnalyticsRoute,
  LibrarianDevicesRoute: LibrarianDevicesRoute,
  LibrarianKiosksRoute: LibrarianKiosksRoute,
  LibrarianReportsRoute: LibrarianReportsRoute,
  LibrarianSettingsRoute: LibrarianSettingsRoute,
  LibrarianStudentsRoute: LibrarianStudentsRoute,
  LibrarianIndexRoute: LibrarianIndexRoute,
}

const LibrarianRouteWithChildren = LibrarianRoute._addFileChildren(
  LibrarianRouteChildren,
)

interface StudentRouteChildren {
  StudentCheckInRoute: typeof StudentCheckInRoute
  StudentDevicesRoute: typeof StudentDevicesRoute
  StudentHistoryRoute: typeof StudentHistoryRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentCheckInRoute: StudentCheckInRoute,
  StudentDevicesRoute: StudentDevicesRoute,
  StudentHistoryRoute: StudentHistoryRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckInSuccessRoute: CheckInSuccessRoute,
  KioskRoute: KioskRoute,
  LibrarianRoute: LibrarianRouteWithChildren,
  LibrarianLoginRoute: LibrarianLoginRoute,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
